# inbuilt libraries
import os
from dotenv import load_dotenv

# third-party libraries
from flask import Flask, jsonify
from flask_sqlalchemy import SQLAlchemy

from flask_smorest import Api
from flask_jwt_extended import JWTManager

# custom libraries
from blocklist import BLOCKLIST
from geospatial_api.models.db import db
from geospatial_api.resources.geometry import blp as GeometryBlueprint
from geospatial_api.resources.user import blp as UsersBlueprint
from geospatial_api.resources.free_geocoding import blp as FreeGeoCodingBlueprint


def create_app():

    if not os.path.exists(".env"):
        return Exception("No .env file found with postgres credentials."\
                         "Its required to run this app.")

    load_dotenv()

    app = Flask(__name__)

    app.config["PROPAGATE_EXCEPTIONS"] = True
    app.config["API_TITLE"] = "REST API for Geospatial Data"
    app.config["API_VERSION"] = "v1"
    app.config["OPENAPI_VERSION"] = "3.0.3"
    app.config["OPENAPI_URL_PREFIX"] = "/"
    app.config["SQLALCHEMY_DATABASE_URI"] = ""

    app.config["SQLALCHEMY_DATABASE_URI"] = (
        f"postgresql://{os.getenv('DATABASE_USER')}:{os.getenv('DATABASE_PASSWORD')}@"
        f"{os.getenv('DATABASE_HOST')}/{os.getenv('DATABASE_NAME')}"
    )

    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

    db.init_app(app)

    api = Api(app)

    with app.app_context():
        db.create_all()

    # Generated by secrets.SystemRandom().getrandbits(128)
    app.config["JWT_SECRET_KEY"] = "18179310603353847870991650577440422880"
    jwt = JWTManager(app)

    @jwt.token_in_blocklist_loader
    def check_if_token_in_blocklist(jwt_header, jwt_payload):
        return jwt_payload["jti"] in BLOCKLIST

    @jwt.revoked_token_loader
    def revoke_token_callback(jwt_header, jwt_payload):
        return (
            jsonify(
                {"description": "The token has been revoked.", "error": "token_revoked"}
            ),
            401,
        )

    @jwt.needs_fresh_token_loader
    def token_not_fresh_callback(jwt_header, jwt_payload):
        return jsonify(
            {"description": "The token is not fresh.", "error": "fresh_token_required"}
        )

    @jwt.expired_token_loader
    def expired_token_callback(jwt_header, jwt_payload):
        return (
            jsonify({"message": "The token has expired.", "error": "token_expired"}),
            401,
        )

    @jwt.invalid_token_loader
    def invalid_token_callback(error):
        return (
            jsonify(
                {"message": "Signature verification failed.", "error": "invalid_token."}
            ),
            401,
        )

    @jwt.unauthorized_loader
    def missing_token_callback(error):
        return (
            jsonify(
                {
                    "description": "Request does not contain an access token.",
                    "error": "authorization_required",
                }
            ),
            401,
        )

    # Registrando as interações dos usuários com a API
    api.register_blueprint(GeometryBlueprint)
    api.register_blueprint(UsersBlueprint)
    api.register_blueprint(FreeGeoCodingBlueprint)

    return app



if __name__ == "__main__":
    app = create_app()
    app.run(debug=True)
