version: "3"

services:
  # Postgis
  postgis:
    image: postgis/postgis:12-3.0
    container_name: postgis
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "54432:5432"
    restart: "unless-stopped"
    networks:
      - bdc_net

  # Flask backend
  flask-backend:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: geo-api
    ports:
      - "5000:5000"
    depends_on:
      postgis:
        condition: service_healthy
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: postgis
      DATABASE_NAME: ${DATABASE_NAME}
    networks:
      - bdc_net

networks:
  bdc_net:
    driver: bridge
